### ISSUE TITLE
边界的bug

### ISSUE THREAD

**Issue by sucongCJS** [Chan-Chun/Cellular-Automaton#2]
包含三个格子的一条水平线紧靠着右边界运行会异常

**Comment by Chan-Chun** [comment]
是的，这就是你提到的边界问题

**Comment by Chan-Chun** [comment]
相关问题 
Duplicate of #4

**Comment by Chan-Chun** [comment]
问题修复：[修复链接](https://github.com/Chan-Chun/Cellular-Automaton/commit/780c8b59c450d0fc07545e5533f2a61752a90095)
