### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by sucongCJS** [Chan-Chun/Cellular-Automaton#4]
您好, 我想请问一下, let new_map = Array(52).fill(Array(52).fill(0)).map((i) => i.map((j) => 0)); 中的 .map((i) => i.map((j) => 0))的作用是什么

**Comment by Chan-Chun** [comment]
因为会存在边界问题，当时只是直接把实际边界扩大成52，渲染边界还是50。
Duplicate of #2
